### PR TITLE
Update to Wepback 3

### PR DESCRIPTION
**Pull request by pirelenito**
The biggest improvement it brings is **scope hoisting**:

> Because scope hoisting will remove function wrappers around your modules, you may see some small size improvements. However, the significant improvement will be how fast the JavaScript loads in the browser.

For more information check: https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b

And although it is a major release of Webpack, it isn't exactly an API breaking change, so upgrading should be fairly smooth. I guess the v9 release will be outpaced pretty quickly.

### CODE REVIEW

**Comment by pirelenito** [comment]
@npejo you have a pretty big project with Sagui, could you try it out and post what improvements it brings in comparison with v9? ❤️

**Comment by pirelenito** [comment]
It looks like we might encounter an issue: https://mobile.twitter.com/i/web/status/877378116028514304

**Comment by pirelenito** [comment]
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/548

**Comment by npejo** [comment]
Thanks for preparing this branch @pirelenito, I will check it on our project.

**Comment by xaviervia** [comment]
I’m labeling this as in progress until we investigate that issue more

**Comment by pirelenito** [comment]
We're just waiting for the 3.0.0 release of extract-text-webpack-plugin, that should be out by tomorrow.

**Pull request merged**
