### PR TITLE
Add flowtype support

### PR DESCRIPTION
**Pull request by xaviervia**
- [x] Add `typecheck` action and task (working)
- [x] Add template for `.flowconfig`
- [x] Merge the PR for fixing dependency issues in [`eslint-config-sagui`](https://github.com/saguijs/eslint-config-sagui/pull/3) and bump dependency in `package.json`
- [x] Paste the `.flowconfig` template into the new projects
- [x] Add `typecheck` action to pipelines (test, build, dist, ...?)
- [x] Add flag to enable type checking all files (not just `@flow` comment)
- [x] Add README entry about flowtype support
  - [x] Mention in https://github.com/saguijs/sagui#npm-scripts
  - [x] Mention in https://github.com/saguijs/sagui#testing-and-quality
  - [x] Mention configuration option for `typeCheckAll` in https://github.com/saguijs/sagui#javascripttranspiledependencies
- [ ] Ensure it works on Windows

Tasks that might be done in a second iteration extending functionality:

- [ ] Verify how to work with [interfaces](https://flowtype.org/docs/third-party.html), since they require an entry on the `.flowconfig` (should that be there by default with `interfaces/` as an empty folder?)
- [ ] Ensure linting rules for flowtype annotations work

### CODE REVIEW

**Comment by pirelenito** [comment]
It looking pretty good! 😀

**Comment by pirelenito** [comment]
The only thing I would suggest changing in your task list is moving "Ensure it works on Windows" to the requirements, now that we have official support.

**Comment by xaviervia** [comment]
Good point. 

All the other items are done now, I'll make sure it works on Windows as well.

**Comment by xaviervia** [comment]
```
  × No binary found matching your system. It's probably not supported.
  × flow binary test failed
```

On Windows 10. [`flow-bin` does not support windows 😞  ](https://github.com/flowtype/flow-bin#flow-bin-)

**Comment by xaviervia** [comment]
For proceeding I think we should disable type checking on Windows. Until `flow-bin` provides support I guess there's no much we can do

**Comment by xaviervia** [comment]
This is the closest I could find to already made Windows builds, but they are significantly outdated: http://www.ocamlpro.com/pub/ocpwin/flow-builds/

**Comment by fhelwanger** [comment]
There's some unofficial builds that are more up to date here: https://github.com/facebook/flow/issues/6#issuecomment-229897350.

Anyway, I think it'd be better to just disable type checking on Windows for now, until it's official.

Also, great work! Sagui is awesome! :tada:

**Comment by xaviervia** [comment]
Thanks for the reference! I'm afraid it wouldn't be the safest thing to automatically pull a custom unsigned build from google drive folder though. It would be better to have all the pipeline in the open and a signed build in result to install it automatically. We can add the option of provide the binary in the path and use it if available, or see if we can make that build (I imagine we could do that with AppVeyor, although I haven't really explored if AppVeyor supports doing that (and the effort to maintain such pipeline might fall out of scope of Sagui). Since exploring this will take some time and we are aiming at testing flowtype in an RC release before promoting it, I think we can merge this PR and keep working on that as a separate issue.

**Comment by xaviervia** [comment]
@fhelwanger this is the follow up issue: https://github.com/saguijs/sagui/issues/179

I manual tested the fix and it works, if the build passes I'll merge and publish as RC.

**Comment by xaviervia** [comment]
This was published in the `sagui@beta` npm channel with the version `6.3.0-rc.0`. The version will be promoted to `6.3.0` and latest once we used it in projects for a while, to ensure is doesn't break the rest of sagui's behavior for consumers now using flow.

**Pull request merged**
