### PR TITLE
Add publicPath support for pages

### PR DESCRIPTION
**Pull request by xaviervia**
Work in progress for fixing #270

### CODE REVIEW

**Comment by pirelenito** [comment]
I think it makes sense! I've actually seen projects in the wild using Sagui and setting it up directly via `webpack.output.publicPath`, but I think it is nice that we provide it as an official public API.

**Comment by pirelenito** [comment]
We could also offer this configuration as simply `publicPath` and not necessarily nested in the `pages`. wdyt?

It would also make the change a lot simpler, while keeping the same API.

**Comment by xaviervia** [comment]
What about the libraries? Should those also be affected by the `publicPath` config? I didn't so it at the root because I felt there was no need for this feature in the libraries.

**Comment by xaviervia** [comment]
Yeah I agree about it being good as a public API, I think we should probably add a note in the README explaining the special case for React Router.

**Comment by pirelenito** [comment]
I agree with both your points. Lets stick it as part of the `pages` API and document it properly.

**Pull request merged**
