### PR TITLE
[RFC] Add handler for unknown commands

### PR DESCRIPTION
**Pull request by abdulhannanali**
### Summary

Right now, as @pirelenito mentioned in #360 we need a handler for unknown actions, which cause the sagui to exit with non zero code, alerting the developers about the problems if any in their setup or sagui. This adds a very minimalistic solution in sagui.

However, I do have a few suggestions, we can use to improve this even further. I hope @pirelenito can look into it too after vacation. 
- Add helpful `Did you mean` messages, in order to tell the user, about the nearest matching option if any
- Maybe it should automatically redirect to `--help`

If the current solution is good enough, it's okay too. :+1: I am using exit code 1 in this case.

### CODE REVIEW

**Comment by xaviervia** [comment]
Thanks a lot! This is a great first step. I think redirecting to `--help` is a good idea; of course adding suggestions would be really nice, but I don’t know what the complexity if that would be. Maybe there is a simple library to handle that.

**Comment by Kadrei** [comment]
one could easily calculate the [levenstheindistance](https://en.wikipedia.org/wiki/Levenshtein_distance) and suggest the one command with the least.

**Comment by xaviervia** [comment]
Cool, I did find a couple of Levenshtein distance calculator functions:

- https://github.com/hiddentao/fast-levenshtein
- https://github.com/gf3/Levenshtein
- https://gist.github.com/andrei-m/982927#gistcomment-586471

I assume one can run whatever command the user sent and compute the distance to all the possible commands, and if one goes below a threshold (say, 3) output that one as a suggestion; otherwise, show the `--help`

Makes sense?

**Comment by pirelenito** [comment]
I think that the PR is great as it is, given this fixes the more urgent problem.

Regarding @xaviervia's suggestion, could we have it as a separated PR?

Wdyt?

Thanks again @abdulhannanali.

**Comment by xaviervia** [comment]
I agree with you @pirelenito , I think this is good as it is. Refinements can come as separate releases. Go for it if you want.

**Comment by pirelenito** [comment]
@abdulhannanali please update your branch from `v9`, I did a fix that should make your build green (#363)

**Comment by abdulhannanali** [comment]
@pirelenito Sounds good, I will do it as a separate PR. Thanks a lot @Kadrei for suggestions. I am going to

**Comment by abdulhannanali** [comment]
@pirelenito Did that, hope the build passes.

**Pull request merged**
